# Generated by Django 6.0 on 2026-07-18 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_percent', models.FloatField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read_by_parent', models.BooleanField(default=False)),
                ('is_read_by_faculty', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='people.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
