# Generated by Django 6.0.7 on 2026-07-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_require_admission_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_number',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated, permanent 12-digit enrollment number.', max_length=12, null=True, unique=True),
        ),
    ]
