# Generated by Django 6.0 on 2026-07-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='max_score',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
