# Generated by Django 6.0 on 2026-07-10 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exam_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject this exam covers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='core.subject'),
        ),
    ]
