# Generated by Django 6.0 on 2026-07-17 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exam_subject'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='people.facultyprofile'),
        ),
    ]
