# Generated by Django 6.0.7 on 2026-07-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_backfill_department_codes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('university', 'code'), ('university', 'name')},
        ),
    ]
