# Generated by Django 6.0 on 2026-07-28 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_department_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('last_serial', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_number_sequences', to='core.department')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_number_sequences', to='core.university')),
            ],
            options={
                'unique_together': {('university', 'department', 'prefix')},
            },
        ),
    ]
